language: python
python:
  - 3.6
notifications:
  email: false
  
install:
  - pip install pep8 
  - pip install autopep8

script:
  - num_errors_before=`find . -name \*.py -exec pep8 --ignore=E402 {} + | wc -l`
  - echo $num_errors_before

  - cd "$TRAVIS_BUILD_DIR"
  - git config --global user.email "fury.00812@gmail.com"
  - git config --global user.name "fury00812"
  - git checkout $TRAVIS_BRANCH

  - find . -name \*.py -exec autopep8 --recursive --aggressive --in-place {} +
  - num_errors_after=`find . -name \*.py -exec pep8 --ignore=E402 {} + | wc -l`
  - echo $num_errors_after

  - |
    if (( $num_errors_after < $num_errors_before )); then
        git commit -a -m "PEP-8 Fix"
        git config --global push.default simple
        git push --quiet
    fi
  - cd "$TRAVIS_BUILD_DIR"

  - find . -name \*.py -exec pep8 --ignore=E402 {} +
